src/Admin/ProjectBundle/Entity/Attachment.php
<?php

namespace Admin\ProjectBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Attachment
 *
 * @ORM\Table(name="project_attachment")
 * @Vich\Uploadable
 * @ORM\Entity(repositoryClass="Admin\ProjectBundle\Repository\AttachmentRepository")
 */
class Attachment
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="project_attachment", fileNameProperty="name")
     *
     * @var File
     */
    private $file;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var int
     *
     * @ORM\Column(name="size", type="integer")
     */
    private $size;

    /**
     * @var string
     *
     * @ORM\Column(name="mime_type", type="string", length=255)
     */
    private $mimeType;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @var Project
     *
     * @ORM\ManyToOne(targetEntity="Admin\ProjectBundle\Entity\Project", inversedBy="attachments", cascade={"persist"})
     * @ORM\JoinColumn(name="project_id", referencedColumnName="id", nullable=false)
     */
    private $project;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Attachment
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set size
     *
     * @param integer $size
     *
     * @return Attachment
     */
    public function setSize($size)
    {
        $this->size = $size;

        return $this;
    }

    /**
     * Get size
     *
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Set mimeType
     *
     * @param string $mimeType
     *
     * @return Attachment
     */
    public function setMimeType($mimeType)
    {
        $this->mimeType = $mimeType;

        return $this;
    }

    /**
     * Get mimeType
     *
     * @return string
     */
    public function getMimeType()
    {
        return $this->mimeType;
    }

    /**
     * @return string
     */
    public function getMimeTypeName()
    {
        $mimeTypes = array(
            'text' => [
                'text/plain',
                'application/rtf'
            ],
            'code' => [
                'text/html',
                'text/html',
                'text/html',
                'text/css',
                'text/css',
                'application/javascript',
                'application/json',
                'application/xml',
                'application/x-shockwave-flash',
                'video/x-flv'
            ],
            'image' => [
                'image/png',
                'image/jpeg',
                'image/gif',
                'image/bmp',
                'image/vnd.microsoft.icon',
                'image/tiff',
                'image/tiff',
                'image/svg+xml',
                'image/svg+xml',
                'image/vnd.adobe.photoshop',
                'application/postscript',
                'application/postscript',
                'application/postscript',
                'application/vnd.oasis.opendocument.image'
            ],
            'archive' => [
                'application/zip',
                'application/x-rar-compressed',
                'application/x-msdownload',
                'application/x-msdownload',
                'application/vnd.ms-cab-compressed'
            ],
            'audio' => [
                'audio/mpeg'
            ],
            'video' => [
                'video/quicktime',
                'video/quicktime'
            ],
            'pdf' => [
                'application/pdf'
            ],
            'word' => [
                'application/msword',
                'application/vnd.oasis.opendocument.text'
            ],
            'excel' => [
                'application/vnd.ms-excel',
                'application/vnd.oasis.opendocument.formula',
                'application/vnd.oasis.opendocument.spreadsheet'
            ],
            'powerpoint' => [
                'application/vnd.ms-powerpoint'
            ],
        );

        foreach ($mimeTypes as $name => $mimeType) {
            if (in_array($this->getMimeType(), $mimeType)) {
                return $name;
            }
        }
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     * @return $this
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $file
     *
     * @return Attachment
     */
    public function setFile(File $file = null)
    {
        $this->file = $file;

        if ($file) {
            $this->setUpdatedAt(new \DateTime());
            $this->setMimeType($file->getMimeType());
            $this->setSize($file->getSize());
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @return Project
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * @param Project $project
     * @return $this
     */
    public function setProject(Project $project)
    {
        $this->project = $project;

        return $this;
    }
}

src/Admin/ProjectBundle/Entity/Project.php
<?php

namespace Admin\ProjectBundle\Entity;

use Admin\ChatBundle\Entity\Thread;
use Admin\MainBundle\Model\Entity as BaseEntity;
use Admin\SaleBundle\Entity\OrderItem;
use Admin\UserBundle\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Project
 *
 * @ORM\Table(name="project")
 * @ORM\Entity(repositoryClass="Admin\ProjectBundle\Repository\ProjectRepository")
 */
class Project extends BaseEntity
{
    const STATUS_PENDING = 0x002;
    const STATUS_CANCELED = 0x003;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=false)
     */
    private $description;

    /**
     * @var Thread
     *
     * @ORM\OneToOne(targetEntity="Admin\ChatBundle\Entity\Thread", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="chat_thread_id", referencedColumnName="id", nullable=false)
     */
    private $talk;

    /**
     * @var OrderItem
     *
     * @ORM\OneToOne(targetEntity="Admin\SaleBundle\Entity\OrderItem", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="sale_order_item_id", referencedColumnName="id", nullable=false)
     */
    private $saleOrderItem;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(
     *     targetEntity="Admin\ProjectBundle\Entity\Attachment",
     *     mappedBy="project",
     *     cascade={"persist", "remove"}, orphanRemoval=true
     * )
     */
    private $attachments;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="delivered_at", type="datetime", nullable=true)
     */
    private $deliveredAt;

    /**
     * @var integer
     *
     * @ORM\Column(name="progress", type="smallint", nullable=false, options={"default":0})
     */
    private $progress = 0;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="Admin\UserBundle\Entity\User")
     * @ORM\JoinColumn(name="assigned_id", referencedColumnName="id", nullable=true)
     */
    private $assignedTo;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="due_date", type="datetime", nullable=true)
     */
    private $dueDate;


    public function __construct()
    {
        $this->attachments = new ArrayCollection();
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Project
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return Thread
     */
    public function getTalk()
    {
        return $this->talk;
    }

    /**
     * @param Thread $talk
     * @return Project
     */
    public function setTalk($talk)
    {
        $this->talk = $talk;

        return $this;
    }

    /**
     * @return OrderItem
     */
    public function getSaleOrderItem()
    {
        return $this->saleOrderItem;
    }

    /**
     * @param OrderItem $saleOrderItem
     * @return Project
     */
    public function setSaleOrderItem($saleOrderItem)
    {
        $this->saleOrderItem = $saleOrderItem;

        return $this;
    }

    /**
     * @param Attachment $attachment
     * @return $this
     */
    public function addAttachment(Attachment $attachment)
    {
        $this->attachments->add($attachment);
        $attachment->setProject($this);

        return $this;
    }

    /**
     * @param Attachment $attachment
     * @return Project
     */
    public function removeAttachment(Attachment $attachment)
    {
        $this->attachments->removeElement($attachment);

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getAttachments()
    {
        return $this->attachments;
    }

    /**
     * @return \DateTime
     */
    public function getDeliveredAt()
    {
        return $this->deliveredAt;
    }

    /**
     * @param \DateTime $deliveredAt
     * @return Project
     */
    public function setDeliveredAt($deliveredAt)
    {
        $this->deliveredAt = $deliveredAt;

        return $this;
    }

    /**
     * @return int
     */
    public function getProgress()
    {
        return $this->progress;
    }

    /**
     * @param int $progress
     * @return Project
     */
    public function setProgress($progress)
    {
        $this->progress = $progress;

        return $this;
    }

    /**
     * @return User
     */
    public function getAssignedTo()
    {
        return $this->assignedTo;
    }

    /**
     * @param User $assignedTo
     *
     * @return $this
     */
    public function setAssignedTo(User $assignedTo = null)
    {
        $this->assignedTo = $assignedTo;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDueDate()
    {
        return $this->dueDate;
    }

    /**
     * @param \DateTime $dueDate
     * @return $this
     */
    public function setDueDate($dueDate)
    {
        $this->dueDate = $dueDate;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return $this
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    public function getStatusList()
    {
        return [
                Project::STATUS_PENDING => 'Pending',
                Project::STATUS_CANCELED => 'Canceled'
            ] + parent::getStatusList();
    }
}

src/Admin/ProjectBundle/Controller/DefaultController.php
<?php

namespace Admin\ProjectBundle\Controller;

use Admin\ProjectBundle\Entity\Attachment;
use Admin\ProjectBundle\Entity\Project;
use Admin\ProjectBundle\Form\ProjectType;
use Doctrine\ORM\EntityManager;
use JMS\SecurityExtraBundle\Annotation\Secure;
use JMS\SecurityExtraBundle\Annotation\SecureParam;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="project_index")
     * @param Request $request
     * @Secure(roles="ROLE_ADMIN")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(Request $request)
    {
        /** @var EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        $qb = $em->getRepository(Project::class)->createQueryBuilder('p');

        $query = $qb->orderBy('p.createdAt', 'DESC')->getQuery();

        $paginator = $this->get('knp_paginator');
        $projects = $paginator->paginate(
            $query,
            $request->get('page', 1)/*page number*/,
            $request->get('limit', 50)/*limit per page*/
        );

        return $this->render('AdminProjectBundle:Default:index.html.twig', [
            'projects' => $projects
        ]);
    }

    /**
     * @Route("/my", name="project_my")
     * @param Request $request
     * @Secure(roles="ROLE_USER")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function myAction(Request $request)
    {
        /** @var EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        $paginator = $this->get('knp_paginator');
        $projects = $paginator->paginate(
            $em->getRepository(Project::class)->getQueryFindByUser($this->getUser()),
            $request->get('page', 1)/*page number*/,
            $request->get('limit', 50)/*limit per page*/
        );

        return $this->render('AdminProjectBundle:Default:index.html.twig', [
            'projects' => $projects
        ]);
    }


    /**
     * Finds and displays a product entity.
     *
     * @Route("/{id}", name="project_show")
     * @Method("GET")
     * @Secure(roles="ROLE_USER")
     *
     * @param Project $project
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showAction(Project $project)
    {
        return $this->render('AdminProjectBundle:Default:show.html.twig', array(
            'project' => $project
        ));
    }

    /**
     * Finds and displays a product entity.
     *
     * @Route("/{id}/messages", name="project_talk")
     * @Method({"GET", "POST"})
     * @Secure(roles="ROLE_USER")
     *
     * @param Project $project
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function talkAction(Project $project)
    {
        $thread = $project->getTalk();

        $form = $this->container->get('fos_message.reply_form.factory')->create($thread);
        $formHandler = $this->container->get('fos_message.reply_form.handler');
        $message = $formHandler->process($form);

        if ($message) {
            $this->redirectToRoute('project_talk', ['id' => $project->getId()]);
        }

        return $this->render('AdminProjectBundle:Default:talk.html.twig', array(
            'form' => $form->createView(),
            'project' => $project,
            'thread' => $project->getTalk()
        ));
    }

    /**
     * Displays a form to edit an existing product entity.
     *
     * @Route("/{id}/edit", name="project_edit")
     * @Method({"GET", "POST"})
     * @Secure(roles="ROLE_USER")
     *
     * @param Request $request
     * @param Project $project
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, Project $project)
    {
        $editForm = $this->createForm(ProjectType::class, $project);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->get('admin_main.flash')->success('message.success.edit');

            return $this->redirectToRoute('project_edit', array('id' => $project->getId()));
        }

        return $this->render('AdminProjectBundle:Default:edit.html.twig', array(
            'project' => $project,
            'edit_form' => $editForm->createView()
        ));
    }
}

src/Admin/ProjectBundle/Resources/views/Default/edit.html.twig
{% extends 'admin/base.html.twig' %}

{% set page_title = 'page.title.edit'|trans({'%entity%': 'entity.project'|trans}) %}

{% block title %}{{ page_title }}{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    {{ form_start(edit_form, { 'attr': {'class': 'form-horizontal form-label-left'} }) }}
                    {{ form_widget(edit_form) }}
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">{{ 'form.actions.edit'|trans }}</button>
                        <a class="btn btn-success" href="{{ path('project_show', {'id': project.id}) }}">{{ 'form.actions.show'|trans }}</a>
                        <a class="btn btn-default" href="{{ path('project_my') }}">{{ 'form.actions.back'|trans }}</a>
                    </div>
                    {{ form_end(edit_form) }}
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
{% endblock %}

src/Admin/ProjectBundle/Resources/views/Default/index.html.twig
{% extends 'admin/base.html.twig' %}

{% set page_title = 'page.title.list'|trans({'%entity%': 'myprojects'|trans}) %}

{% block title %}{{ page_title }}{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    {% if projects.items is empty %}
                        <table class="table">
                            <tbody>
                            <tr>
                                <td colspan="10">
                                    {{ 'result.empty'|trans }}
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    {% else %}
                        <!-- start project list -->
                        <table class="table table-striped projects">
                            <thead>
                            <tr>
                                <th style="width: 1%">#</th>
                                <th style="width: 40%">Nome do Projeto</th>
                                <th>Responsável</th>
                                <th>Mensagens</th>
                                <th>Progresso</th>
                                <th>Situação</th>
                                <th style="width: 15%">Ações</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for project in projects %}
                                <tr>
                                    <td>{{ project.id }}</td>
                                    <td>
                                        <a href="{{ path('project_show', { 'id': project.id }) }}">
                                            {{ project.name }}
                                            <br/>
                                            <small>{{ 'Createdat'|trans }} {{ project.createdAt|localizeddate('short') }}</small>
                                        </a>
                                    </td>
                                    <td>
                                        {% if project.assignedTo %}
                                            <ul class="list-inline">
                                                <li>
                                                    <img src="{{ vich_uploader_asset(project.assignedTo.person, 'imageFile') | default(asset('assets/images/user.png')) | imagine_filter('small') }}"
                                                         alt="Avatar" title="{{ project.assignedTo.realname }}">
                                                </li>
                                            </ul>
                                        {% else %}
                                            <label>--</label>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a href="{{ path('project_talk', { 'id': project.id }) }}">
                                            Messages <span class="label label-info">Nova</span>
                                        </a>
                                    </td>
                                    <td class="project_progress">
                                        <div class="progress progress_sm">
                                            <div class="progress-bar bg-green" role="progressbar"
                                                 data-transitiongoal="{{ project.progress }}" aria-valuenow="{{ project.progress }}" style="width: {{ project.progress }}%;"></div>
                                        </div>
                                        <small>{{ project.progress }}% Completo</small>
                                    </td>
                                    <td>
                                        <label class="label label-success">{{ project.statusList[project.status]|trans }}</label>
                                    </td>
                                    <td>
                                        <a href="{{ path('project_edit', { 'id': project.id }) }}" class="btn btn-info btn-xs">
                                            <i class="fa fa-pencil" aria-hidden="true"></i> {{ 'form.actions.edit'|trans }}
                                        </a>
                                        <a href="{{ path('project_show', { 'id': project.id }) }}" class="btn btn-primary btn-xs">
                                            <i class="fa fa-eye" aria-hidden="true"></i> {{ 'form.actions.show'|trans }}
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->

{% endblock %}

src/Admin/ProjectBundle/Resources/views/Default/show.html.twig
{% extends 'admin/base.html.twig' %}

{% set page_title = 'Detalhes do projeto' %}

{% block title %}{{ page_title }}{% endblock %}

{% set months = ['este', 'a um', 'a dois', 'a três', 'a quatro'] %}

{% block page_content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h4>{{ project.name }}</h4>
                </div>
                <div class="x_content">
                    <div class="col-md-9 col-sm-9 col-xs-12">

                        <ul class="stats-overview">
                            <li>
                                <span class="name">Orçamento</span>
                                <span class="value text-success">{{ project.saleOrderItem.total|localizedcurrency(currency) }}</span>
                            </li>
                            <li>
                                <span class="name">Duração estimada do projeto</span>
                                <span class="value text-success"> {% if project.dueDate %}{{ project.dueDate|localizeddate('short') }}{% else %}Sem previsão{% endif %}</span>
                            </li>
                        </ul>
                        <br/>

                        <div>

                            <h4>Mensagens Recente</h4>

                            <!-- end of user messages -->
                            <ul class="messages">
                                {% for message in project.talk.messages.slice(0, 5) %}
                                    <li id="message_{{ message.id }}">
                                        <img class="avatar" src="{{ vich_uploader_asset(message.sender.person, 'imageFile') | default(asset('assets/images/user.png')) | imagine_filter('small') }}" alt="Avatar" title="{{ message.sender.realname }}">
                                        <div class="message_date">
                                            <h3 class="date text-info">{{ message.createdAt|date('d') }}</h3>
                                            <p class="month">{{ message.createdAt|date('M') }}</p>
                                        </div>
                                        <div class="message_wrapper">
                                            <h4 class="heading">{{ message.sender.realname }}</h4>
                                            <blockquote class="message">{{ message.body }}</blockquote>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                            <!-- end of user messages -->

                        </div>

                    </div>

                    <!-- start project-detail sidebar -->
                    <div class="col-md-3 col-sm-3 col-xs-12">

                        <section class="panel">

                            <div class="x_title">
                                <h2>Descrição do Projeto</h2>
                                <div class="clearfix"></div>
                            </div>
                            <div class="panel-body">
                                <p>{% if project.description %}{{ project.description }}{% else %}<i>Sem descrição</i>{% endif %}</p>

                                <br/>
                                <div class="project_detail">
                                    <p class="title">Cliente</p>
                                    <p>{{ project.createdBy.realname }}</p>
                                    <p class="title">Criado em</p>
                                    <p>{{ project.createdAt|date('d M Y') }}</p>
                                    <p class="title">Situação</p>
                                    {%  set y = date().diff(date(project.createdAt)).y %}
                                    <p>Iniciado {% if y in months|keys %}{{ months[y] }} mês{% else %}a alguns meses{% endif %}</p>
                                </div>

                                <br />
                                <h5>Arquivos do projeto</h5>
                                <ul class="list-unstyled project_files">
                                    {% if project.attachments.count %}
                                        {% for attachment in project.attachments %}
                                            <li>
                                                <a href="{{ vich_uploader_asset(attachment, 'file') }}" download="{{ attachment.name }}">
                                                    <i class="fa fa-file-{{ attachment.mimeTypeName }}-o"></i> {{ attachment.name }}
                                                </a>
                                            </li>
                                        {% endfor %}
                                    {% else %}
                                        <li><i>Nenhum arquivo anexado</i></li>
                                    {% endif %}
                                </ul>
                                <br/>
                                <div class="text-center mtop20">
                                    <a href="{{ path('project_edit', { 'id': project.id }) }}" class="btn btn-sm btn-success btn-block">Editar informações</a>
                                </div>
                            </div>

                        </section>

                    </div>
                    <!-- end project-detail sidebar -->
                </div>
                <div class="x_footer">
                    <a class="btn btn-default" href="{{ path('project_my') }}">{{ 'form.actions.back'|trans }}</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->

{% endblock %}

src/Admin/ProjectBundle/Resources/views/Default/talk.html.twig
{% extends 'admin/base.html.twig' %}

{% set page_title = thread.subject %}

{% block title %}{{ page_title }}{% endblock %}
{% block page_content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h4>Mensagens</h4>
                </div>
                <div class="x_content">
                    <ul class="messages">
                        {% for message in thread.messages %}
                            <li id="message_{{ message.id }}">
                                <img class="avatar"
                                     src="{{ vich_uploader_asset(message.sender.person, 'imageFile') | default(asset('assets/images/user.png')) | imagine_filter('small') }}"
                                     alt="Avatar"
                                     title="{{ message.sender.realname }}">
                                <div class="message_date">
                                    <h3 class="date text-info">{{ message.createdAt|date('d') }}</h3>
                                    <p class="month">{{ message.createdAt|date('M') }}</p>
                                </div>
                                <div class="message_wrapper">
                                    <h4 class="heading">{{ message.sender.realname }}</h4>
                                    <blockquote class="message">{{ message.body }}</blockquote>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>

                    <h3>{% trans from 'FOSMessageBundle' %}reply{% endtrans %}</h3>

                    <form action="{{ url('project_talk', {'id': project.id}) }}" method="post">
                        {{ form_widget(form) }}

                        <input type="submit" class="btn btn-default"/>
                    </form>
                </div>
                <div class="x_footer">
                    <a class="btn btn-default" href="{{ path('project_my') }}">{{ 'form.actions.back'|trans }}</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
{% endblock %}